apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-back
  namespace: node-back
spec:
  selector:
    matchLabels:
      app: node-back
  template:
    metadata:
      labels:
        app: node-back
    spec:
      containers:
        - name: node-back
          image: ghcr.io/do3-2023/node-back-mbo:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: '512Mi'
              cpu: '500m'
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: 'PGUSER'
              value: 'postgres'
            - name: 'PGPASSWORD'
              value: 'CHANGE_ME'
            - name: 'PGHOST'
              value: 'postgres.data.svc.cluster.local'
            - name: 'PGPORT'
              value: '5432'
          readinessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 5000
          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 15
            httpGet:
              path: /healthz
              port: 5000
