apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-front
spec:
  selector:
    matchLabels:
      app: next-front
  template:
    metadata:
      labels:
        app: next-front
    spec:
      containers:
        - name: next-front
          image: ghcr.io/do3-2023/next-front-mbo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: next-front
